language: python

dist: focal
services:
  - xvfb
addons:
  apt:
    sources:
    - STABLE=10.0.6
    - EXPERIMENTAL=10.5a4
    - TBB_DIST_URL=https://www.torproject.org/dist/torbrowser/
  matrix:
    - TRAVIS_EXTRA_JOB_WORKAROUND=true
cache:
  directories:
  - ${DOWNLOAD_DIR}

jobs:

  - TRAVIS_EXTRA_JOB_WORKAROUND=true

  include:

    - name: "Linux Python 3.6 on EXPERIMENTAL en-US tar"
      os: linux
      env: VERSION_ARCH="${EXPERIMENTAL}/tor-browser-linux64-${EXPERIMENTAL}_en-US.tar.xz"
      python: 3.6
    - name: "Linux Python 3.6 on EXPERIMENTAL zh-CN tar"
      os: linux
      env: VERSION_ARCH="${EXPERIMENTAL}/tor-browser-linux64-${EXPERIMENTAL}_zh-CN.tar.xz"
      python: 3.6
    install:
      - pip install -r requirements-travis.txt
      - pip install .
      - TARBALL=`echo ${VERSION_ARCH} |cut -d'/' -f 2`
      - . ./travis.sh
      - locale="_"`echo $TARBALL |cut -d'_' -f 2 | cut -d'.' -f 1`
      - export TBB_PATH=${HOME}/tor-browser${locale}
    before_script:
      - cd tbselenium
    script: travis_retry py.test -s -v --cov=tbselenium --cov-report term-missing --durations=10 test



sudo: false
language: python
os: linux
dist: focal
services:
  - xvfb
addons:
  apt:
    sources:
    - STABLE=10.0.6
    - EXPERIMENTAL=10.5a4
    - TBB_DIST_URL=https://www.torproject.org/dist/torbrowser/
  matrix:
    - TRAVIS_EXTRA_JOB_WORKAROUND=true
cache:
  directories:
  - ${DOWNLOAD_DIR}
matrix:
